name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5

      - name: Setup Phix
        run: .github/bin/setup-phix
        env:
          PHIX_VERSION: 1.0.5
          PHIX_SHA: 57179171dbed    # ??

      - name: Verify all exercises
        run: bin/verify-exercises
